#!/bin/sh -f

bush_home=`pwd`/../../bush

save_dir=`pwd`

#/////////////////////////////////////////////////////////////
#/// cleanup comres //////////////////////////////////////////
#/////////////////////////////////////////////////////////////
${bush_home}/find_rm ../comres '*.*'
#/////////////////////////////////////////////////////////////
#/// get some files from ioda and put them in comres /////////
#/////////////////////////////////////////////////////////////

cd ..

from=../ioda/res

if [ ! -d ${from} ] ; then
  echo "directory ${from} not found"
  exit
fi

files=""
files="${files} arialbd.ttf helveticabd.ttf courbd.ttf lucidagrandebd.ttf" #gui fonts.
files="${files} helvetica.ttf"

# cam panel :
files="${files} move2red.jpg crazyeye_run.jpg flip_flop.jpg"
files="${files} close.jpg edit.jpg edit_undo.jpg"

# main gui :
files="${files} go_home_large.jpg turn_around.jpg"
files="${files} movie_camera.jpg system_config_boot.jpg"

# rwc items :
files="${files} sidebar_photos.jpg stop_diaporama.jpg"
files="${files} cursor.jpg"

# main menu :
files="${files} files.jpg application_exit.jpg"
files="${files} connect_to_wall.jpg"
files="${files} edit_clear.jpg edit_undo.jpg"
files="${files} move2red.jpg flip_flop.jpg"
files="${files} object_rotate_left.jpg stop_object_rotate_left.jpg"
files="${files} document_export.jpg"
files="${files} routing_step.jpg console.jpg tools.jpg"

files="${files} location_ftp.jpg white.jpg"
#files="${files} det_to_wall.jpg"
#files="${files} disconnect_from_wall.jpg"

for file in ${files} ; do
  /bin/cp ${from}/${file} ./comres/.
done

/bin/cp ${from}/ioda.style ./comres/inexlib_serv.style

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////
files="inexlib_serv.ftp inexlib_serv.scenarios"
files="${files} event.jpg clear_event.jpg stop_events.jpg vis_events.jpg"
files="${files} icon.jpg"

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ${bush_home}/and_app_res
. ${bush_home}/ios_app_res
